# Generated by Django 6.0.6 on 2026-06-12 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('downloads', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('automated', 'Automatisé'), ('manual', 'Manuel')], default='manual', max_length=20)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('opened', models.BooleanField(default=False)),
                ('open_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.prospect')),
            ],
        ),
        migrations.DeleteModel(
            name='ContentIdea',
        ),
        migrations.DeleteModel(
            name='EmailCampaign',
        ),
    ]
