# Generated by Django 6.0.6 on 2026-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentresource_emaillog_delete_contentidea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentresource',
            name='is_lead_magnet',
            field=models.BooleanField(default=False),
        ),
    ]
