# Generated by Django 6.0.6 on 2026-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securitylog_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text="Jour d'envoi après l'inscription (ex: 1, 3, 7)", unique=True)),
                ('title', models.CharField(help_text='Titre interne (ex: Bienvenue)', max_length=255)),
                ('subject', models.CharField(help_text="Sujet de l'email envoyé au prospect", max_length=255)),
                ('body', models.TextField(help_text="Contenu de l'email")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
