# Generated by Django 6.0.6 on 2026-06-13 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailsequencestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.prospect'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.prospect'),
        ),
    ]
